# Generated by Django 3.1.7 on 2026-04-30 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='devicecars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('IPAD', 'iPad'), ('CHROMEBOOK', 'Chromebook'), ('SURFACE', 'Surface Go'), ('ACER', 'Acer 小筆電')], max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('open_use', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('target_class', models.CharField(max_length=20)),
                ('class_size', models.IntegerField()),
                ('date', models.DateField()),
                ('period', models.CharField(choices=[('1', '第1節'), ('2', '第2節'), ('3', '第3節'), ('4', '第4節'), ('NOON', '午休'), ('5', '第5節'), ('6', '第6節'), ('7', '第7節'), ('8', '第8節'), ('OTHER', '其他')], max_length=10)),
                ('device_type', models.CharField(max_length=20)),
                ('sign_time', models.DateTimeField(auto_now_add=True)),
                ('assigned_cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.devicecars')),
            ],
        ),
    ]
